version: '3.1'
services:
  #Web Server
   webserver:
     image: nginx:alpine
     container_name: web-server
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"
   #DB Server
   db:
     image: mysql:5.7
     container_name: db-server
     restart: unless-stopped
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: defualt
       MYSQL_USER: user
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password
secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

volumes:
    db_data:
